name: rsw_fleet_manager
description: "RSW Fleet Manager - Flutter App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.9.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: any
  provider: ^6.1.2
  sqflite: ^2.3.3
  path: ^1.9.0
  uuid: ^4.4.0
  pdf: ^3.10.7
  printing: ^5.13.4
  fl_chart: ^0.68.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
